apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  strategy:
    canary:
      canaryService: demo-canary
      stableService: demo
      trafficRouting:
        istio:
          virtualService:
            name: demo-vs
            routes:
            - default
      steps:
      - setWeight: 10
      - pause: { duration: 10 }
      - setWeight: 30
      - pause: { duration: 10 }
      - setWeight: 100
  template:
    metadata:
      labels:
        app: demo
        version: v1
    spec:
      containers:
      - name: demo
        image: ghcr.io/fullstackjam/demo:v1
        imagePullPolicy: Never
        env:
        - name: VERSION
          value: "v1"
        ports:
        - containerPort: 8080
